indent = 4
always_for_in = true
whitespace_typedefs = true
remove_extra_newlines = true
whitespace_in_kwargs = false
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = true
conditional_to_if = true
trailing_comma = true
join_lines_based_on_source = true